- name: Common | Update apt cache (Debian/Ubuntu)
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600
  when: ansible_os_family == "Debian"

- name: Common | Install essential packages (Debian/Ubuntu)
  ansible.builtin.apt:
    name:
      - python3-pip
      - python3-dev       
      - libpq-dev         
      - python3-venv      
      - curl              
    state: present
  when: ansible_os_family == "Debian"
